services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/smart-leads
      JWT_SECRET: 7c9e5490510dd98fe52a13caa9aedd15837145825bda1ba0c0509a9c91ac5505ff0eaa1c63f50e9aefaf94a448fcfb55aba64426eab1743191df82140adff4fc
      JWT_EXPIRES_IN: 7d
      PORT: 5000
      CLIENT_URL: http://localhost:5173
    ports:
      - "5000:5000"

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:5000/api
    depends_on:
      - server
    ports:
      - "5173:80"

volumes:
  mongo-data:
